//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenisKortProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int id { get; set; }
        public Nullable<int> Rezervation { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> isPaid { get; set; }
    
        public virtual Rezervation Rezervation1 { get; set; }
    }
}
